FROM debian:bullseye-slim

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake \
    wget \
    git \
    build-essential \
    libpqxx-dev \
    postgresql-server-dev-13

